### ISSUE TITLE
BROKEN EWW

### ISSUE THREAD

**Issue by ramaxpublic** [niraj998/dots#1]
![Screenshot_2022-01-13-05-28-21_1366x768](https://user-images.githubusercontent.com/54692455/149313231-1432bcea-3532-4cc4-a0b6-d7d335c33ff5.png)
# HELP!
### as you can see, what i get after install your eww config. how to fix it?
`i was follow the instructions and nothing happen`

**Comment by niraj998** [comment]
can you please clone this repo again I updated eww configs ask again if you still have issue

**Comment by ramaxpublic** [comment]
`Solved thanks!`
